### PR TITLE
Small fix for msg.midi.raw that was truncated.

### PR DESCRIPTION
**Pull request by natcl**
Thanks for merging my previous changes !
Here's a small fix, msg.midi.raw was truncated.

### CODE REVIEW

**Comment by natcl** [comment]
Hello, any chance this could get merged ?

Thanks !

**Comment by urbiworx** [comment]
Sorry for the delay and thanks for reminding. I will try to do this over
the holidays.

Am Dienstag, 20. Dezember 2016 schrieb Nathanaël Lécaudé :

**Comment by urbiworx** [comment]
Thanks for providing this. Happy holidays!

**Comment by natcl** [comment]
Thanks to you !
Happy holidays !

2016-12-26 6:42 GMT-05:00 urbiworx <notifications@github.com>:

**Pull request merged**
